language: java
addons:
  sonarqube: 
    token:
      secure: gP+4oC1o7DhNZW3hnHzginWzrZwQCqhE4guFx2MslumIxci6BORhaL2PIDuk3GTrS+xCu/aYVdqt3NbtXplqRwKy96GSJTgeZN2O1ByslEEouU0uSt6UdpLLVs0qN+SjeZ6V0fBHzZ+LctKc2fDdZwo1kpbRcgO3bfxAZ2U3xiAcUt8RQascmhUSocn1fRoIKKoTdb0sv5YJBlPRN+gyxuBKrhmV63KyoGFI3Y7rVMd7XpqW24qoD+xfD32LQo72hazf1PBdhXUdpzH2L+4m0zhgUzm529s3aUIk/v/drifsVpeGx9AFBsaL0FbgQxnas0suS4xOstRJVJHo1qzbJYRxWfBKWAFnI0SWVetRwkaZSB4mh5rt+qim3dxBkeKpWUOi3naxewO0Vb8ZNqhBq2rqPy6EtDnERCNdyKoRS/15+mywnq0daO+tVfvQ9qyTM0aorGi47YaEENyvSNOn7Bi5j0H+umEtwP5ohkl+m9KkOzwWgBTZjIY3qIqDx3HcFYth7Tfi3W3wJR3SyeoFTVHX+pwIO9tQQKrYRokp4C7I5AsK0fVZmBQhWTMClkSnktcFPcap6HL+IASUVvaTUZfvoZ88yVj4rTrMxRbHpEec1NMRhvgEijmuC2m/ePxHXU5c7gi7HdCcSZhwrTuflFwy7brVWfO3opYdqfcDLXQ=
    github_token:
      secure: sPcZqODEtbIh0hQEEIRp3TEOrZVQfve0LahMqFFylbslSo43sXvqxMAaVG6BdccqtZQtswK08Kd7oiOUt3JWF27QqkusaEZaBUVcmsSrpstoCbCXdlwoKPq/9dKtFSO4Ja7k3WS+aFBUcOd/l6fc6xjIdqvutu0ifVRqwDgHl4d9qLQxTyEtiCpEx5YfPWAK9nnJTFN/nwwfvlgxSa0VDjC+Z80MhVpI3i9ygLDkM8555UnANl0T+Uq/psmrVz6x64KMNEPU9HRAClM99MER6dmWL5yOPR/GcJbYlPsmc+1sk8tEZqgNr1FMte0ID59FrH0XR5YlUiKXmrrgz19OIYCuJBy207wd21jgViLT6qnCGSC+7OQrv2GbyKK5Z6wvlhIbER0Bh/OKYO7M1WJIsTL5VWzdpr3R1kdU7D9V1z/u6rRZr+Aj3LIGGx35k4KOj1I2wVvlV8ZbG8WEl/PT4TWhXbU8p8ffwTKPBFNhsjLmTzP26Z9wAw859RzzIiqdD/uH1xed83aviFf4O/jWtQ3F0Rhvi0HX7YT8jww02KukW5zj9UzHQNyDbktE+nMW/RwLRTXOrjEHzV7o04x30i+wYHetx1TnKiGIbDWD+2xyANwNwxbg4MHPoNtUptHW7PpWC1ceulevH2iJ1RhdFYFIOINM7KC/Nqk17DA3+HI=
jdk:
  - oraclejdk8
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
install:
  - mvn clean --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
script:
  - sonar-scanner
deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/json-parser
      branch: master
      jdk: oraclejdk8
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/json-parser
      tags: true
      jdk: oraclejdk8
notifications:
  email: false
  slack:
    rooms:
      - secure: p47PlTGJHxaIiT0i/PGoBGDfYaqlotK34+JqdKkkA3Oh/UOpEtExnc3TomFVi/CI3ubIk5KcCoTBYAHKhUvZ6sgCsNaZHIFLagy1/IYCy7bBf8tC7snyJJlvqFv3Lwfe/gFssAQdR3Lh3cILMSSNUk6U1Uueyf+SqDFcUXBjbFqotCUet+JUS2qPgoUA7JlYLR6h7GNxe5m97TWhpVeFTetQ94tbzgisOI1JDjpaI/HL9QCv2QLDuViQDtXW3oA6l+LznCV9Hjc+AVXnNNIu2Gdwg6PXrct3TYd0khOEMiCPmnckqWm7ow8i7wgzzks9O2orSJ5JWZ2mXq/CNe3y8G1G0crMBf+jgFFn3y2q1K9rByOGHp2doJZhoFT6CokouYtBYBUiRk+WZOUmvdJc46u1K83KXMlTptk+TkW5qg322N0L5SmOBEjzH9ZY4pWT/4gUuMHzVkV+U8Hw4CpCVAFiENdKA4v3cgeNevJZ4CG39idHemoYQVRNV+Fml4uzA9iaddmwEJYLUCie7W4UWkELL5PpCNGWuk3yVhtD7EDZfhqxjbC04olxxVsLJPyYorOQCWoTlP1UfMIYOLrdpUY3u0jErIiFGeVSgrSCQaRpbYeCwJHRYiOW72ai3AhojaWx/upWx/EtAx1gHhVJuRNNJhkHkEunyvwE58OoxKA=
    on_success: change
    on_failure: always
    template:
      - "Build status: %{message}"
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
