language: java
addons:
  sonarqube: 
    token:
      secure: gP+4oC1o7DhNZW3hnHzginWzrZwQCqhE4guFx2MslumIxci6BORhaL2PIDuk3GTrS+xCu/aYVdqt3NbtXplqRwKy96GSJTgeZN2O1ByslEEouU0uSt6UdpLLVs0qN+SjeZ6V0fBHzZ+LctKc2fDdZwo1kpbRcgO3bfxAZ2U3xiAcUt8RQascmhUSocn1fRoIKKoTdb0sv5YJBlPRN+gyxuBKrhmV63KyoGFI3Y7rVMd7XpqW24qoD+xfD32LQo72hazf1PBdhXUdpzH2L+4m0zhgUzm529s3aUIk/v/drifsVpeGx9AFBsaL0FbgQxnas0suS4xOstRJVJHo1qzbJYRxWfBKWAFnI0SWVetRwkaZSB4mh5rt+qim3dxBkeKpWUOi3naxewO0Vb8ZNqhBq2rqPy6EtDnERCNdyKoRS/15+mywnq0daO+tVfvQ9qyTM0aorGi47YaEENyvSNOn7Bi5j0H+umEtwP5ohkl+m9KkOzwWgBTZjIY3qIqDx3HcFYth7Tfi3W3wJR3SyeoFTVHX+pwIO9tQQKrYRokp4C7I5AsK0fVZmBQhWTMClkSnktcFPcap6HL+IASUVvaTUZfvoZ88yVj4rTrMxRbHpEec1NMRhvgEijmuC2m/ePxHXU5c7gi7HdCcSZhwrTuflFwy7brVWfO3opYdqfcDLXQ=
    github_token:
      secure: UEfQVMysVXzq9O/aEisr5ysSG72dOfMCJVpvwq7TgR83AkC7yEQW0lLazqWco5ES+J1LwZ4LKbz0fR+yR53YWPQgY7VQNscXKEWwm+pBm45xwDSfkSxfLBXWuQktnS4lZ8BNtz/3JGJzk7xGvdfpVay8DT5YQ3MD3Z7nEMO+fkady2GNnRLpAejeBQv97DMU8TjVLZyQTjWwfqCTc2Nf7yDeYWTrJMjXXBjonVPX+X6jngq/T4Cb0MFOt98Q1NLXzRBYJIMxSTn4YwrrHpIQvwf9iTu7IGtVTgUni5xRpQRnaP+NN4xZYZViNFuyxBA8Lt3HuaISKKEFkdWIz90retfOGTjuoKnMb8W5yAw5vVzbqvFt2dE6urmknlgIOYKR7nWmsrXoMCGb3iLl1f3dV7kPMDhduHKuUx35+c+tYwPirqGki9oQw2gJQLeGqsPgPFCHZRFYq5mVaWocYnGQA+V17QGiI00cEX5AVGe855p+WqZtIsSQEWkO9pUNqlIM5B5OGBXDTqJpdF2JCoQVnc0+oTZgEMeAn4ZJa3md6CsSs7OIvDMI1tWofOxmreDWf92Vo1njxaqHiV+8PSyVH2OPQqbPMvfPw9T1KiLeMzjonayDHbFfgfCdkYIS7/YZbZ3/E6MyEVtD2ouvc3ojlI5F352oGk0TLfywvi6T1Dk=
jdk:
  - oraclejdk8
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
install:
  - mvn clean --settings .travis/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip -B -V
script:
  - sonar-scanner
deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/json-parser
      branch: master
      jdk: oraclejdk8
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      repo: sbtqa/json-parser
      tags: true
      jdk: oraclejdk8
notifications:
  email: false
  slack:
    rooms:
      - secure: p47PlTGJHxaIiT0i/PGoBGDfYaqlotK34+JqdKkkA3Oh/UOpEtExnc3TomFVi/CI3ubIk5KcCoTBYAHKhUvZ6sgCsNaZHIFLagy1/IYCy7bBf8tC7snyJJlvqFv3Lwfe/gFssAQdR3Lh3cILMSSNUk6U1Uueyf+SqDFcUXBjbFqotCUet+JUS2qPgoUA7JlYLR6h7GNxe5m97TWhpVeFTetQ94tbzgisOI1JDjpaI/HL9QCv2QLDuViQDtXW3oA6l+LznCV9Hjc+AVXnNNIu2Gdwg6PXrct3TYd0khOEMiCPmnckqWm7ow8i7wgzzks9O2orSJ5JWZ2mXq/CNe3y8G1G0crMBf+jgFFn3y2q1K9rByOGHp2doJZhoFT6CokouYtBYBUiRk+WZOUmvdJc46u1K83KXMlTptk+TkW5qg322N0L5SmOBEjzH9ZY4pWT/4gUuMHzVkV+U8Hw4CpCVAFiENdKA4v3cgeNevJZ4CG39idHemoYQVRNV+Fml4uzA9iaddmwEJYLUCie7W4UWkELL5PpCNGWuk3yVhtD7EDZfhqxjbC04olxxVsLJPyYorOQCWoTlP1UfMIYOLrdpUY3u0jErIiFGeVSgrSCQaRpbYeCwJHRYiOW72ai3AhojaWx/upWx/EtAx1gHhVJuRNNJhkHkEunyvwE58OoxKA=
    on_success: change
    on_failure: always
    template:
      - "Build status: %{message}"
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
